---
output:
    distill::distill_article:
        highlight: kate      ## styling of code
        code_folding: false  ## if 'true' you can expand and shrink code chunks
        toc: true            ## if 'true' adds a table of content
        toc_depth: 2         ## level to be displayed in the table of content
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE,
dev = 'ragg_png', fig.width = 9, fig.height = 6, dpi = 250, retina = 1)

Sys.setlocale('LC_TIME', 'C')

#sapply(list('tidyverse', 'ggplot2', 'raster', 'terra'),
#       library, character.only = TRUE, logical.return = TRUE)
library(patchwork)

`%>%` <- magrittr::`%>%`

ggplot2::theme_set(ggplot2::theme_void())
ggplot2::theme_update(
  legend.position = "top",
  legend.key.width = ggplot2::unit(3.5, "lines"),
  legend.key.height = ggplot2::unit(.5, "lines"),
  plot.margin = ggplot2::margin(rep(10, 4)),
  plot.title = ggplot2::element_text(hjust = .5, face = "bold")
)
```


```{r data-import}
path <- "C:/Users/scherer/PopDynIZW Dropbox/GeoData/data-proc/germany/Roads-germany_2022_100m_03035_tif"

meta <- 
  utils::read.csv2(list.files(path, pattern = '.csv$', recursive = TRUE, full.names = TRUE)) %>%
  dplyr::mutate(dplyr::across(dplyr::everything(), as.character))

tif <- 
  terra::rast(list.files(path, pattern = '.tif$', recursive = TRUE, full.names = TRUE)) %>% 
  terra::aggregate(fact = 20, fun = function(x) ifelse(sum(x, na.rm = TRUE) >= 1, 1, 0)) ## just for now to simulate binary
  #terra::aggregate(fact = 20, fun = function(x) ifelse(sum(x, na.rm = TRUE) >= 1, sum(x, na.rm = TRUE) / 100, 0)) ## just for now to simulate quantitative
  #terra::aggregate(fact = 20, fun = function(x) ifelse(sum(x, na.rm = TRUE) >= 1, floor(sum(x, na.rm = TRUE) / 100), 0)) ## just for now to simulate qualitative
```

```{r data-table, layout='l-page'}
meta_tbl <- 
  meta %>%
  tidyr::pivot_longer(
    cols = dplyr::everything(),
    names_to = 'column', 
    values_to = 'input'
  ) %>%
  flextable::flextable() %>% 
  flextable::autofit()

meta_tbl
```

```{r map}
p_base_map <- 
  ggplot2::ggplot() +
  stars::geom_stars(data = stars::st_as_stars(tif)) +
  ggplot2::coord_sf(expand = FALSE)

meta$data_type <- "binary"

if(meta$data_type == "binary") {
  p_map <- 
    p_base_map + 
    ggplot2::scale_fill_gradient(
      low = "#f1effc", 
      high = "#221462", 
      breaks = as.vector(terra::minmax(tif)), 
      name = NULL
    ) +
    ggplot2::guides(fill = ggplot2::guide_legend(label.position = "bottom"))
}
  
if(meta$data_type == "quantitative") {
  p_map <- 
    p_base_map + 
    ggplot2::scale_fill_gradientn(
      colors = c( "#f1effc", "#583cd7", "#110A31"),
      name = NULL
    ) +
    ggplot2::guides(fill = ggplot2::guide_colorbar(show.limits = TRUE))
  }

if(meta$data_type == "qualitative") {
  p_map <- 
    p_base_map + 
    rcartocolor::scale_fill_carto_c(
      palette = "Bold",
      breaks = as.vector(terra::minmax(tif))[1]:as.vector(terra::minmax(tif))[2],
      name = NULL
    ) +
    ggplot2::guides(fill = ggplot2::guide_legend(label.position = "bottom"))
  }
```


```{r plot, layout='l-screen'}
p_map
```

***

<details><summary>Session Info</summary>

```{r sessionInfo}
Sys.time()
sessionInfo()
```

</details>
