---
title: "D6 Geo Database"
description: |
  This webpage provides a quick look-up source for geospatial data available for studies at the IZW Department of Ecological Dynamics.
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r data, include=FALSE}
library(tidyverse)

# a table that collects all information

data_table <- base::do.call(base::rbind, lapply(list.files(here::here(), pattern = , ".rmd$"), 
                     function(x){
  tibble(path = x) %>% 
  dplyr::mutate(what = unlist(stringi::stri_split(path, regex = "_"))[1],
    origin = unlist(stringi::stri_split(path, regex = "_"))[2],
                year = unlist(stringi::stri_split(path, regex = "_"))[3]) %>% 
  dplyr::mutate(distill = paste0("* [", what, " (", year, ")](/d6geodatabase/reports/",
               gsub(pattern = ".rmd", replacement = ".html", x = path), ")"))
  }))

# a function, thats create the input for the inline code

data_list <- lapply(unique(data_table$origin), function(x){
  tab <- data_table %>%
    dplyr::filter(origin %in% x)
  
  stringi::stri_c(
    stringi::stri_c("<details><summary>", x,"</summary>"),
    stringi::stri_c(tab$distill, collapse = "\n"),
    stringi::stri_c("</details>"), 
    collapse = "\n")

})

```

`r stringi::stri_c(unlist(data_list), collapse = "\n")`


## Contact {.appendix}

Department Lead: Prof. Dr. S. Kramer-Schadt  
Deputy Lead: Dr. Andreas Wilting  
Geo Data Manager: Moritz Wenzler-Meya
<a href="mailto:wenzler@izw-berlin.de">wenzler[at]izw-berlin.de</a>  

## Address {.appendix}

Leibniz Institute for Zoo and Wildlife Research  
Department of Ecological Dynamics  
Alfred-Kowalke-Str. 17  
D-10315 Berlin, Germany 
