---
title: "&nbsp;"
output:
    distill::distill_article:
        highlight: kate      ## styling of code
        code_folding: false  ## if 'true' you can expand and shrink code chunks
        toc: true            ## if 'true' adds a table of content
        toc_depth: 2         ## level to be displayed in the table of content
        keep_md: TRUE
---

[main page](index.html)&ensp;

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE,
dev = 'ragg_png', fig.width = 9, fig.height = 6, dpi = 250, retina = 1)

Sys.setlocale('LC_TIME', 'C')

#sapply(list('tidyverse', 'ggplot2', 'raster', 'terra'),
#       library, character.only = TRUE, logical.return = TRUE)
library(patchwork)

`%>%` <- magrittr::`%>%`

ggplot2::theme_set(ggplot2::theme_void())
ggplot2::theme_update(
  legend.position = 'bottom',
  legend.key.width = ggplot2::unit(3.5, 'lines'),
  legend.key.height = ggplot2::unit(.5, 'lines'),
  plot.margin = ggplot2::margin(rep(10, 4)),
  plot.title = ggplot2::element_text(hjust = .5, face = 'bold')
)
```



```{r data-impor}

# get path
path <-
    'E:/PopDynCloud/GeoData/data-proc/berlin/motorways_berlin_2022_100m_03035_tif'

meta <-
      utils::read.csv(list.files(path, pattern = '.csv$', recursive = TRUE, full.names = TRUE)) %>%
  dplyr::mutate(dplyr::across(dplyr::everything(), as.character))

tif <-
  terra::rast(list.files(path, pattern = '.tif$', recursive = TRUE, full.names = TRUE))

# if(raster::ncell(tif)>= 1e+6){
#   tif <- tif %>%
#   terra::aggregate(fact = 10,
#                    fun = base::ifelse(meta$type_of_data %in% c('binary_categorical',
#                                                        'unordered_categorical',
#                                                        'ordered_categorical'),
#                                 'max',
#                                 'mean'))
# }

```


```{r}
# p_base_map <-
#   ggplot2::ggplot() +
#   stars::geom_stars(data = stars::st_as_stars(tif)) +
#   ggplot2::coord_sf(expand = FALSE)
# 
# base_plot <- p_base_map + ggplot2::scale_fill_gradient(
#   low = "#f1effc",
#   high = "#221462",
#   breaks = as.vector(terra::minmax(tif)),
#   name = NULL,
#   na.value = "grey90"
# ) + ggplot2::guides(fill = ggplot2::guide_legend(label.position = "bottom"))
# 
# saveRDS(base_plot, here::here("img", paste0(unlist(stringi::stri_split(path, regex = "/"))[length(unlist(stringi::stri_split(path, regex = "/")))], ".rds")))

#   ggplot2::ggsave(device = "png", path = here::here("img"),
#                   filename =  paste0(unlist(stringi::stri_split(path, regex = "/"))[length(unlist(stringi::stri_split(path, regex = "/")))], ".png"))
```



```{r data-table}

meta_gt <- gt::gt(meta %>%
  tidyr::pivot_longer(
    cols = dplyr::everything(),
    names_to = 'column',
    values_to = 'input'
  ))
```

```{r map}
p_map <- readRDS(paste(path, paste0(unlist(stringi::stri_split(path, regex = "/"))[length(unlist(stringi::stri_split(path, regex = "/")))], ".rds"), sep = "/"))

```


```{r table}
# p_table <-
#   ggplot2::ggplot() +
#   ggplot2::annotation_custom(
#     grob = grid::rasterGrob(meta_tbl %>% flextable::as_raster()),
#     xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf
#   )
```



```{r, layout='l-screen'}
p_map + plot_annotation(title = gsub("_", " " ,meta$folder_name))
meta_gt
```


<details><summary>Session Info</summary>

```{r sessionInfo}
## DO NOT REMOVE!
## We store the settings of your computer and the current versions of the
## packages used to allow for reproducibility
Sys.time()
#git2r::repository() ## uncomment if you are using GitHub
sessionInfo()
```

</details>
